#!/usr/bin/env zsh

if [ -e "$HOME/.Xresources" ] ; then
    xrdb "$HOME/.Xresources"
fi

xmodmap -e 'keycode any = Hyper_L'
xmodmap -e 'keycode any = Hyper_R'
xmodmap -e 'remove mod4 = Hyper_L'
xmodmap -e 'remove mod4 = Hyper_R'
xmodmap -e 'add mod3 = Hyper_L'
xmodmap -e 'add mod3 = Hyper_R'

xmodmap -e 'keycode any = F35'

#tigervncconfig -set RemapKeys="0x20->0xffed"   # space -> Hyper_L
#xcape -e 'Hyper_L=space'

#tigervncconfig -set RemapKeys="0xff09->0xffed" # Tab -> Hyper_L
#xcape -e 'Hyper_L=Tab'

#tigervncconfig -set RemapKeys="0x5c->0xffee"   # backslash -> Hyper_R 
#xcape -e 'Hyper_R=backslash'

# xcape -e 'Control_L=F35'

xcape -e 'Super_L=F35;Super_R=F35' # On MacOS VNC, I map the command key to Super_L/R

tigervncconfig -nowin &

exec i3
